### ISSUE TITLE
Place of attaching ID to contect for koa

### ISSUE THREAD

**Issue by vanthome** [wilmoore/request-id.js#1]
Hi,
I want to use the request ID in downstream middleware but
cannot as you yield directly after creating it.
I think the yield should be _after_ setting the request ID to the current context.
If you look at other ID gens, they all do it like this.
Thanks

**Comment by wilmoore** [comment]
Hi @vanthome,

Sorry for the delay. I am not sure how I missed your message. Anyhow, I will take a look at this as soon as I can.

**Comment by MarkHerhold** [comment]
I would tend to agree with @vanthome. Setting the header should be done going downstream in my opinion.

**Comment by madbence** [comment]
@vanthome The id is available at `this.requestId` (or whatever your `paramName` is), but it would be indeed better to attach the header before yielding, eg because the header will be lost if downstream throws an error.

**Comment by vanthome** [comment]
@madbence well, nothing else I said...

**Comment by wilmoore** [comment]
Hey, thanks for taking the time to check this out and comment. I agree with the comments here. I'm happy to accept a PR (the faster route); otherwise, I'll try to get to this sometime this week or this weekend.

Thanks.

**Comment by wilmoore** [comment]
Thanks for the input @vanthome and @MarkHerhold. Thanks for the PR @madbence! Greatly appreciate it.

**Comment by wilmoore** [comment]
Fix included in 0.10.0 - https://github.com/wilmoore/request-id.js/releases/tag/v0.10.0

**Comment by MarkHerhold** [comment]
@wilmoore No, thank you!

**Comment by wilmoore** [comment]
@MarkHerhold :smile:
