### ISSUE TITLE
Koa v2 Support 

### ISSUE THREAD

**Issue by vanthome** [wilmoore/request-id.js#6]
Are you planning to migrate this? A lot of other middlewares are already doing this.

**Comment by wilmoore** [comment]
Actually, the plan was to re-write this so it is less framework specific and would be easy to integrate with any lib/framework.

To that end, if you have any suggestions, I'm happy to hear them.

**Comment by wilmoore** [comment]
BTW, I already have a prototype, I just need time to clean it up, write tests, docs, etc.

**Comment by vanthome** [comment]
Hmm, you are supporting different frameworks already and I like the approach. I also don't see how that can be reduced. Looking forward to a native Koa v2 variant.

**Comment by wilmoore** [comment]
Have a look at the following article. I'm still editing but I plan to publish it soon:
https://medium.com/@wilmoore/a08157653911

**Comment by vanthome** [comment]
Hi Will,
I read it and have to say I disagree.
I think middleware looses its appeal if you cannot just do 

``` js
app.use(someMw( {   config props  }));
```

Also people are used to it and expect this.
I agree with the general issue you pint out.
I see two possible solutions:
- Have three modules - functionality, koa and express middlewares 
- Bundle those server framework specific modules (koa, express, ...) in the module with the functionality

**Comment by wilmoore** [comment]
> I read it and have to say I disagree.

That's fair. I am expecting such a response initially from people that are happy with how things have been. Change is not easy.

> I think middleware looses its appeal if you cannot just do...

Most people will just copy the default settings from the `README.md` which is fine and won't change anything. Those that need the extra flexibility, get to do as they wish with it.

Also, this approach does not preclude anyone from just wrapping it in a framework-specific manner and publishing it to the npm registry and telling people to do `app.use(plugin({}));`.

> Also people are used to it and expect this.

Change is hard and it isn't for everyone. That's fine.

> Have three modules - functionality, koa and express middlewares

Like I said, I probably won't write middleware this way anymore, but that does not preclude anyone from wrapping my generic middleware functions. I won't be duplicating middleware for connect, express, koa, and hapi.

This approach is the current status quo and what is expected but it's flawed.
